Homework 4 (GCP Bastion)
Otus-DevOps-2018-02/whoisfdv_infra pull request #3
Opened 2018-03-21 20:23 UTC by whoisfdv

# Выполнено ДЗ №4

 - [ ] Основное ДЗ
 - [ ] Доп. задание

## В процессе сделано:
 - В GCP создано 2 виртуальных хоста bastion и someinternalhost;
bastion_IP = 104.155.21.19
someinternalhost_IP = 10.132.0.3
 - На хосте bastion установлен и сконфигурирован VPN (Pritunl);

## Как проверить работоспособность:
 - Подключится к VPN на хосте bastion используя конфигурационный файл cloud-bastion.ovpn и реквизиты указанные в ДЗ;

## PR checklisk
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2018-03-21 20:40 UTC, whoisfdv commented
 Проверка TravisCI пройдена успешно. Обе ВМ на стороне GCP остановил.

2018-03-22 10:33 UTC, chromko requested changes
Поправь, пожалуйста скрипт.
В остальном все ок  - когда поменяешь - одобрим

2018-03-22 10:33 UTC, chromko commented on setupvpn.sh
> +appuser@bastion:~$
лишнего многовато в скрипте. Так он работать точно не будет

2018-03-23 06:48 UTC, whoisfdv commented
Случайным образом внес в файл лишние строки.
Поправил, сделал fix-коммит, прогнал повторные тест TravisCI.

2018-03-29 12:21 UTC, chromko approved these changes
Теперь все ок, работа принята

2018-03-31 02:08 UTC, merged